### PR TITLE
feat: implement gitleaks

### PR DESCRIPTION
**Pull request by loispostula**
closes https://github.com/ForesightMiningSoftwareCorporation/infrastructure/issues/122

### CODE REVIEW

**Review by greaka — APPROVED** [review]
We need to watch out. Github only allows 20 custom workflows in one run, and we are getting close to the limit. So this would probably be one of the first workflows that we will break up eventually.

**Comment by loispostula** [comment]
Can you point me to the doc stating that limit?

**Comment by greaka** [comment]
Here you go: https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

**Comment by loispostula** [comment]
Ah indeed, I was planning on enabling this workflow through required workflowsd, so it would not be a reusable workflow

**Pull request merged**
